import type {
  CountryDemand,
  Course,
  DeliveryMode,
  Employer,
  EvidenceItem,
  Learner,
  PassportEntry,
  Role_,
  Track,
  TrackId,
} from "./types";

export const modeLabels: Record<DeliveryMode, string> = {
  onsite: "Onsite",
  live: "Live tutor-led",
  "self-paced": "Self-paced",
};

export const modeBlurbs: Record<DeliveryMode, string> = {
  onsite: "In a hub classroom with a tutor and classmates",
  live: "Scheduled online sessions with a live tutor",
  "self-paced": "Work through it on your own timetable",
};

export const tracks: Track[] = [
  {
    id: "data",
    name: "Data Analytics",
    tagline: "Turn messy records into decisions people act on.",
    demandIndex: 92,
  },
  {
    id: "software",
    name: "Software Engineering",
    tagline: "Build the interfaces and services people use daily.",
    demandIndex: 88,
  },
  {
    id: "cloud",
    name: "Cloud & Infrastructure",
    tagline: "Keep services running, deploy without drama.",
    demandIndex: 81,
  },
  {
    id: "security",
    name: "Cybersecurity",
    tagline: "Protect the systems a country now runs on.",
    demandIndex: 86,
  },
  {
    id: "business",
    name: "Digital Business",
    tagline: "Find customers online and keep them.",
    demandIndex: 74,
  },
  {
    id: "climate",
    name: "Climate & Agriculture Tech",
    tagline: "Put data behind farms, water and weather.",
    demandIndex: 69,
  },
  {
    id: "fintech",
    name: "Fintech Operations",
    tagline: "Move money safely for people without a bank branch.",
    demandIndex: 83,
  },
  {
    id: "ai",
    name: "AI & Emerging Tech",
    tagline: "Use AI tools with judgement, not hype.",
    demandIndex: 78,
  },
];

export const trackById = (id: TrackId) =>
  tracks.find((t) => t.id === id) ?? tracks[0];

export const courses: Course[] = [
  {
    slug: "data-analytics-foundations",
    title: "Data Analytics Foundations",
    track: "data",
    level: "Foundation",
    blurb:
      "Start from a spreadsheet and finish with a dashboard a manager actually uses.",
    description:
      "You will work with real-shaped datasets from Gambian utilities, clinics and markets — the kind that arrive incomplete and inconsistent. Each module ends with a piece of evidence that goes into your Skills Passport, reviewed by a tutor rather than auto-graded.",
    weeks: 12,
    hoursPerWeek: 8,
    modes: ["onsite", "live", "self-paced"],
    hub: "Ednovate Lab, Kanifing",
    tutor: "Fatoumatta Jallow",
    tutorTitle: "Lead tutor, Data practice",
    skills: [
      "Spreadsheet modelling",
      "SQL querying",
      "Data cleaning",
      "Dashboard design",
      "Data storytelling",
    ],
    learners: 412,
    rating: 4.8,
    openRoles: 37,
    feeGMD: 4500,
    scholarship: "Full scholarship for 40 places per cohort",
    modules: [
      {
        name: "Reading a dataset honestly",
        summary:
          "What a column actually means, where records go missing, and how to say so out loud.",
        competencies: ["Data profiling", "Documenting assumptions"],
        hours: 14,
      },
      {
        name: "Cleaning without lying",
        summary:
          "Deduplication, type coercion and the ethics of filling a blank cell.",
        competencies: ["Data cleaning", "Reproducible transforms"],
        hours: 18,
      },
      {
        name: "Asking questions in SQL",
        summary: "Joins, aggregates and window functions against a live warehouse.",
        competencies: ["SQL querying", "Joins and aggregation"],
        hours: 22,
      },
      {
        name: "Dashboards people read",
        summary:
          "Chart choice, labelling, and cutting three charts down to the one that matters.",
        competencies: ["Dashboard design", "Chart selection"],
        hours: 20,
      },
      {
        name: "Capstone: a decision memo",
        summary:
          "One dataset, one recommendation, defended in a ten-minute review with a tutor.",
        competencies: ["Data storytelling", "Stakeholder review"],
        hours: 22,
      },
    ],
  },
  {
    slug: "front-end-web-development",
    title: "Front-End Web Development",
    track: "software",
    level: "Foundation",
    blurb:
      "Ship a working, accessible web app on a phone-first connection.",
    description:
      "Built around the constraint that most of your users are on a mid-range Android phone and metered data. You will build four projects, each reviewed line by line, and finish with a deployed app you can hand to an employer.",
    weeks: 16,
    hoursPerWeek: 10,
    modes: ["onsite", "live", "self-paced"],
    hub: "Ednovate Lab, Kanifing",
    tutor: "Ebrima Darboe",
    tutorTitle: "Lead tutor, Software practice",
    skills: [
      "HTML & CSS",
      "JavaScript",
      "React",
      "Accessibility",
      "Performance budgets",
    ],
    learners: 356,
    rating: 4.7,
    openRoles: 29,
    feeGMD: 5200,
    scholarship: "Half fee waiver for continuing learners",
    modules: [
      {
        name: "Markup that holds up",
        summary: "Semantic HTML, forms that work without JavaScript, real labels.",
        competencies: ["HTML semantics", "Accessible forms"],
        hours: 18,
      },
      {
        name: "Layout on a small screen",
        summary: "Flexbox, grid and designing up from 360px wide.",
        competencies: ["Responsive layout", "CSS architecture"],
        hours: 24,
      },
      {
        name: "JavaScript you can debug",
        summary: "State, events, fetch, and reading a stack trace calmly.",
        competencies: ["JavaScript fundamentals", "Debugging"],
        hours: 30,
      },
      {
        name: "Components with React",
        summary: "Props, state, lists and splitting a screen into parts.",
        competencies: ["React components", "Client state"],
        hours: 32,
      },
      {
        name: "Capstone: ship it",
        summary:
          "Deploy a four-screen app under a 200KB budget and defend the trade-offs.",
        competencies: ["Performance budgets", "Deployment"],
        hours: 36,
      },
    ],
  },
  {
    slug: "cloud-and-devops-essentials",
    title: "Cloud & DevOps Essentials",
    track: "cloud",
    level: "Intermediate",
    blurb: "Take an app from your laptop to something that stays up.",
    description:
      "For learners who can already build something small and now need it to survive other people using it. Heavy on Linux, containers and the boring discipline of monitoring.",
    weeks: 14,
    hoursPerWeek: 9,
    modes: ["live", "self-paced"],
    hub: "Online cohort",
    tutor: "Ousman Camara",
    tutorTitle: "Tutor, Platform engineering",
    skills: ["Linux", "Docker", "CI/CD", "Observability", "Cost control"],
    learners: 184,
    rating: 4.6,
    openRoles: 21,
    feeGMD: 6400,
    scholarship: "Employer-sponsored places available",
    modules: [
      {
        name: "The command line as home",
        summary: "Files, permissions, processes, logs and ssh without fear.",
        competencies: ["Linux administration", "Shell scripting"],
        hours: 20,
      },
      {
        name: "Containers, honestly explained",
        summary: "Images, layers, volumes and why your build works only on your machine.",
        competencies: ["Docker", "Reproducible builds"],
        hours: 24,
      },
      {
        name: "Pipelines that catch mistakes",
        summary: "Automated tests, environments and a deploy you can undo.",
        competencies: ["CI/CD", "Rollback strategy"],
        hours: 26,
      },
      {
        name: "Knowing when it breaks",
        summary: "Metrics, alerts, on-call etiquette and writing an incident note.",
        competencies: ["Observability", "Incident response"],
        hours: 22,
      },
    ],
  },
  {
    slug: "cybersecurity-fundamentals",
    title: "Cybersecurity Fundamentals",
    track: "security",
    level: "Foundation",
    blurb: "Learn how systems get broken into, so you can close the door.",
    description:
      "Defensive from the first week. You will run a real phishing simulation, harden a small network, and write the kind of security brief a bank or ministry will actually read.",
    weeks: 12,
    hoursPerWeek: 8,
    modes: ["onsite", "live"],
    hub: "Ednovate Lab, Banjul",
    tutor: "Isatou Bah",
    tutorTitle: "Lead tutor, Security practice",
    skills: [
      "Threat modelling",
      "Network hardening",
      "Incident reporting",
      "Identity & access",
      "Security awareness",
    ],
    learners: 231,
    rating: 4.8,
    openRoles: 26,
    feeGMD: 5800,
    scholarship: "Public-sector staff attend free",
    modules: [
      {
        name: "How attacks actually start",
        summary: "Phishing, reused passwords, and the human layer first.",
        competencies: ["Threat modelling", "Security awareness"],
        hours: 16,
      },
      {
        name: "Locking down a network",
        summary: "Segmentation, firewalls, patching and default credentials.",
        competencies: ["Network hardening", "Patch management"],
        hours: 22,
      },
      {
        name: "Who is allowed in",
        summary: "Identity, least privilege, MFA and offboarding.",
        competencies: ["Identity & access"],
        hours: 18,
      },
      {
        name: "Writing the brief",
        summary: "Turning a finding into one page a director can act on.",
        competencies: ["Incident reporting"],
        hours: 16,
      },
    ],
  },
  {
    slug: "digital-marketing-and-growth",
    title: "Digital Marketing & Growth",
    track: "business",
    level: "Foundation",
    blurb: "Get a small business its first hundred paying customers online.",
    description:
      "Runs against live budgets. Each learner is paired with a real Serrekunda or Brikama trader for the capstone and reports back on what the spend actually returned.",
    weeks: 10,
    hoursPerWeek: 6,
    modes: ["onsite", "live", "self-paced"],
    hub: "Ednovate Lab, Serrekunda",
    tutor: "Mariama Njie",
    tutorTitle: "Tutor, Digital business",
    skills: [
      "Audience research",
      "Content production",
      "Paid social",
      "Analytics",
      "Conversion copy",
    ],
    learners: 298,
    rating: 4.5,
    openRoles: 18,
    feeGMD: 3800,
    scholarship: "Cooperative rate for market associations",
    modules: [
      {
        name: "Who is actually buying",
        summary: "Interviews, not assumptions. Building one real customer picture.",
        competencies: ["Audience research"],
        hours: 12,
      },
      {
        name: "Making things worth sharing",
        summary: "Shooting on a phone, writing captions, publishing on a schedule.",
        competencies: ["Content production", "Conversion copy"],
        hours: 16,
      },
      {
        name: "Spending money carefully",
        summary: "Small paid tests, reading the numbers, stopping what fails.",
        competencies: ["Paid social", "Budget testing"],
        hours: 18,
      },
      {
        name: "Capstone: a live campaign",
        summary: "Two weeks, a real trader, a real budget and a results readout.",
        competencies: ["Analytics", "Campaign reporting"],
        hours: 14,
      },
    ],
  },
  {
    slug: "agri-data-and-climate-monitoring",
    title: "Agri-Data & Climate Monitoring",
    track: "climate",
    level: "Intermediate",
    blurb: "Put numbers behind rainfall, yields and water in the field.",
    description:
      "Field-heavy. Onsite cohorts spend three weekends in Central River Region collecting and validating their own data before analysing it.",
    weeks: 14,
    hoursPerWeek: 7,
    modes: ["onsite", "live"],
    hub: "Ednovate Lab, Janjanbureh",
    tutor: "Lamin Touray",
    tutorTitle: "Tutor, Climate & agriculture",
    skills: [
      "Field data collection",
      "Geospatial mapping",
      "Remote sensing",
      "Statistics",
      "Reporting to funders",
    ],
    learners: 126,
    rating: 4.7,
    openRoles: 14,
    feeGMD: 4900,
    scholarship: "Funded places for cooperative nominees",
    modules: [
      {
        name: "Collecting data you can trust",
        summary: "Survey design, sensor placement and calibration in the field.",
        competencies: ["Field data collection", "Calibration"],
        hours: 20,
      },
      {
        name: "Mapping what you found",
        summary: "QGIS basics, coordinate systems and honest map colours.",
        competencies: ["Geospatial mapping"],
        hours: 24,
      },
      {
        name: "Watching from above",
        summary: "Free satellite imagery for rainfall, vegetation and water stress.",
        competencies: ["Remote sensing"],
        hours: 22,
      },
      {
        name: "Reporting to people who fund it",
        summary: "Turning a season of data into a brief a ministry or donor uses.",
        competencies: ["Reporting to funders", "Statistics"],
        hours: 18,
      },
    ],
  },
  {
    slug: "mobile-money-and-fintech-operations",
    title: "Mobile Money & Fintech Operations",
    track: "fintech",
    level: "Intermediate",
    blurb: "Run the rails that move money for people with no bank branch.",
    description:
      "Built with operations leads from regional payment providers. Covers reconciliation, fraud patterns, agent networks and the compliance paperwork that decides whether a product ships.",
    weeks: 12,
    hoursPerWeek: 8,
    modes: ["live", "self-paced"],
    hub: "Online cohort",
    tutor: "Binta Sowe",
    tutorTitle: "Tutor, Fintech operations",
    skills: [
      "Payments reconciliation",
      "Fraud detection",
      "KYC & compliance",
      "Agent network operations",
      "Customer dispute handling",
    ],
    learners: 173,
    rating: 4.6,
    openRoles: 23,
    feeGMD: 6100,
    scholarship: "Sponsored by partner providers",
    modules: [
      {
        name: "Where the money sits",
        summary: "Float, ledgers, settlement windows and why balances disagree.",
        competencies: ["Payments reconciliation"],
        hours: 20,
      },
      {
        name: "Patterns that mean fraud",
        summary: "Velocity checks, SIM swap, agent collusion and what to escalate.",
        competencies: ["Fraud detection"],
        hours: 22,
      },
      {
        name: "Knowing your customer",
        summary: "Identity documents, tiered limits and regional AML expectations.",
        competencies: ["KYC & compliance"],
        hours: 20,
      },
      {
        name: "Keeping agents working",
        summary: "Liquidity, commissions, training and dispute turnaround.",
        competencies: ["Agent network operations", "Customer dispute handling"],
        hours: 18,
      },
    ],
  },
  {
    slug: "ai-product-literacy",
    title: "AI Product Literacy for Teams",
    track: "ai",
    level: "Foundation",
    blurb: "Use AI tools with judgement — and know when not to.",
    description:
      "A short course for people already in a job. What these tools do, where they fail, what you must never paste into them, and how to check an answer before you forward it.",
    weeks: 6,
    hoursPerWeek: 4,
    modes: ["live", "self-paced"],
    hub: "Online cohort",
    tutor: "Modou Ceesay",
    tutorTitle: "Tutor, AI practice",
    skills: [
      "Prompt design",
      "Output verification",
      "Data handling",
      "Automation design",
      "AI policy writing",
    ],
    learners: 341,
    rating: 4.4,
    openRoles: 11,
    feeGMD: 2900,
    scholarship: "Team rate for five or more staff",
    modules: [
      {
        name: "What it is doing",
        summary: "A plain explanation of prediction, and why it sounds confident.",
        competencies: ["AI fundamentals"],
        hours: 8,
      },
      {
        name: "Asking well",
        summary: "Context, examples, constraints and iterating on a prompt.",
        competencies: ["Prompt design"],
        hours: 10,
      },
      {
        name: "Checking the answer",
        summary: "Verification habits, citations and spotting a confident mistake.",
        competencies: ["Output verification"],
        hours: 10,
      },
      {
        name: "Rules for your team",
        summary: "Drafting a one-page AI policy your colleagues will follow.",
        competencies: ["Data handling", "AI policy writing"],
        hours: 8,
      },
    ],
  },
  {
    slug: "applied-data-storytelling",
    title: "Applied Data Storytelling",
    track: "data",
    level: "Advanced",
    blurb: "Make the number land with the person who can act on it.",
    description:
      "The follow-on to Foundations. Less about queries, more about the fifteen minutes where you have to convince a director. Every session ends in a live critique.",
    weeks: 8,
    hoursPerWeek: 6,
    modes: ["live", "self-paced"],
    hub: "Online cohort",
    tutor: "Fatoumatta Jallow",
    tutorTitle: "Lead tutor, Data practice",
    skills: [
      "Narrative structure",
      "Executive briefing",
      "Visual design",
      "Uncertainty communication",
      "Live critique",
    ],
    learners: 97,
    rating: 4.9,
    openRoles: 16,
    feeGMD: 5400,
    scholarship: "Free for Foundations graduates",
    modules: [
      {
        name: "One sentence, then the chart",
        summary: "Leading with the finding instead of the method.",
        competencies: ["Narrative structure"],
        hours: 12,
      },
      {
        name: "Designing for a projector",
        summary: "Contrast, labels, and removing everything that is not the point.",
        competencies: ["Visual design"],
        hours: 14,
      },
      {
        name: "Saying what you do not know",
        summary: "Confidence intervals in plain language, and refusing false precision.",
        competencies: ["Uncertainty communication"],
        hours: 10,
      },
      {
        name: "The room itself",
        summary: "Handling interruptions, hostile questions and the follow-up email.",
        competencies: ["Executive briefing", "Live critique"],
        hours: 12,
      },
    ],
  },
];

export const courseBySlug = (slug: string) =>
  courses.find((c) => c.slug === slug);

export const employers: Employer[] = [
  {
    id: "banjul-data",
    name: "Banjul Data Collective",
    sector: "Analytics consultancy",
    location: "Banjul",
    country: "The Gambia",
    blurb:
      "A twelve-person analytics team serving utilities and health programmes across the Greater Banjul Area.",
    hiring: 4,
  },
  {
    id: "kombo-fintech",
    name: "Kombo Fintech",
    sector: "Payments",
    location: "Serrekunda",
    country: "The Gambia",
    blurb:
      "Mobile wallet and agent network with 900 active agents between Bakau and Brikama.",
    hiring: 6,
  },
  {
    id: "yonna-cloud",
    name: "Yonna Cloud Services",
    sector: "Managed IT",
    location: "Kanifing",
    country: "The Gambia",
    blurb:
      "Hosting and managed infrastructure for schools, clinics and small banks.",
    hiring: 3,
  },
  {
    id: "senegambia-agri",
    name: "Senegambia Agri Analytics",
    sector: "Agriculture technology",
    location: "Farafenni",
    country: "The Gambia",
    blurb:
      "Yield and rainfall monitoring for groundnut and rice cooperatives along the river.",
    hiring: 2,
  },
  {
    id: "sunu-energy",
    name: "Sunu Energy",
    sector: "Renewable energy",
    location: "Dakar",
    country: "Senegal",
    blurb:
      "Solar mini-grid operator running 60 sites across Senegal and southern Mauritania.",
    hiring: 5,
  },
  {
    id: "atlantic-ridge",
    name: "Atlantic Ridge Logistics",
    sector: "Logistics",
    location: "Accra",
    country: "Ghana",
    blurb: "Port-to-inland freight coordination with a growing data team.",
    hiring: 3,
  },
  {
    id: "sahel-health",
    name: "Sahel Health Informatics",
    sector: "Health technology",
    location: "Freetown",
    country: "Sierra Leone",
    blurb:
      "Clinic record systems and outbreak reporting for district health teams.",
    hiring: 4,
  },
];

export const employerById = (id: string) =>
  employers.find((e) => e.id === id);

export const openRoles: Role_[] = [
  {
    id: "role-1",
    title: "Junior Data Analyst",
    employerId: "banjul-data",
    location: "Banjul, The Gambia",
    mode: "Hybrid",
    salaryGMD: "D14,000 – D18,000 / month",
    posted: "4 days ago",
    requires: ["SQL querying", "Data cleaning", "Dashboard design"],
    rationale:
      "Three of the four competencies they screen on are already verified in your passport, including the SQL work Fatoumatta signed off in week 9.",
    trackFit: "data",
  },
  {
    id: "role-2",
    title: "Reporting Officer, Utilities Programme",
    employerId: "banjul-data",
    location: "Kanifing, The Gambia",
    mode: "Onsite",
    salaryGMD: "D12,500 – D15,000 / month",
    posted: "1 week ago",
    requires: ["Data profiling", "Data cleaning", "Data storytelling"],
    rationale:
      "Your profiling and cleaning evidence got you the introduction. The storytelling competency is the one they will probe, so finish the capstone memo before the interview.",
    trackFit: "data",
  },
  {
    id: "role-3",
    title: "Payments Operations Associate",
    employerId: "kombo-fintech",
    location: "Serrekunda, The Gambia",
    mode: "Onsite",
    salaryGMD: "D13,000 – D16,500 / month",
    posted: "2 days ago",
    requires: ["Payments reconciliation", "Data cleaning", "Fraud detection"],
    rationale:
      "Reconciliation is a data-cleaning job in disguise — your verified cleaning evidence covers their entry requirement.",
    trackFit: "fintech",
  },
  {
    id: "role-4",
    title: "Front-End Developer (Junior)",
    employerId: "kombo-fintech",
    location: "Serrekunda, The Gambia",
    mode: "Hybrid",
    salaryGMD: "D15,000 – D20,000 / month",
    posted: "5 days ago",
    requires: ["React components", "Accessible forms", "Performance budgets"],
    rationale:
      "They build for low-bandwidth Android users, which is the constraint the Front-End capstone is graded on.",
    trackFit: "software",
  },
  {
    id: "role-5",
    title: "Monitoring & Evaluation Assistant",
    employerId: "senegambia-agri",
    location: "Farafenni, The Gambia",
    mode: "Onsite",
    salaryGMD: "D11,000 – D14,000 / month",
    posted: "1 week ago",
    requires: ["Field data collection", "Statistics", "Reporting to funders"],
    rationale:
      "Cooperative reporting season starts in October and they hire from verified field-data evidence first.",
    trackFit: "climate",
  },
  {
    id: "role-6",
    title: "Infrastructure Support Engineer",
    employerId: "yonna-cloud",
    location: "Kanifing, The Gambia",
    mode: "Onsite",
    salaryGMD: "D16,000 – D21,000 / month",
    posted: "3 days ago",
    requires: ["Linux administration", "Docker", "Incident response"],
    rationale:
      "They accept the Cloud & DevOps incident note as a substitute for two years of experience.",
    trackFit: "cloud",
  },
  {
    id: "role-7",
    title: "Data Analyst, Mini-Grid Performance",
    employerId: "sunu-energy",
    location: "Dakar, Senegal",
    mode: "Remote",
    salaryGMD: "XOF 420,000 – 560,000 / month",
    posted: "6 days ago",
    requires: ["SQL querying", "Dashboard design", "Uncertainty communication"],
    rationale:
      "Remote-first and open to Gambian candidates — the first ECOWAS role matched from a Banjul cohort.",
    trackFit: "data",
  },
  {
    id: "role-8",
    title: "Security Analyst (Entry)",
    employerId: "sahel-health",
    location: "Freetown, Sierra Leone",
    mode: "Hybrid",
    salaryGMD: "SLE 4,800 – 6,200 / month",
    posted: "2 weeks ago",
    requires: ["Threat modelling", "Identity & access", "Incident reporting"],
    rationale:
      "District health data is being centralised and they need defenders who can write a readable brief.",
    trackFit: "security",
  },
  {
    id: "role-9",
    title: "Growth Associate",
    employerId: "atlantic-ridge",
    location: "Accra, Ghana",
    mode: "Remote",
    salaryGMD: "GHS 4,200 – 5,500 / month",
    posted: "1 week ago",
    requires: ["Audience research", "Paid social", "Campaign reporting"],
    rationale:
      "Your live campaign results readout is the only portfolio piece they ask for.",
    trackFit: "business",
  },
];

export const initialPassport: PassportEntry[] = [
  {
    id: "pp-1",
    competency: "Data profiling",
    courseSlug: "data-analytics-foundations",
    evidenceTitle: "NAWEC billing extract — profile & gaps memo",
    evidenceSummary:
      "Profiled 18 months of billing records, found 2,140 duplicate meter readings and documented every assumption before touching a value.",
    status: "verified",
    verifiedBy: "Fatoumatta Jallow",
    verifiedOn: "12 May 2026",
    employerViews: 7,
  },
  {
    id: "pp-2",
    competency: "Data cleaning",
    courseSlug: "data-analytics-foundations",
    evidenceTitle: "Reproducible cleaning notebook",
    evidenceSummary:
      "A documented pipeline that takes the raw extract to an analysis-ready table, with every transform reversible and commented.",
    status: "verified",
    verifiedBy: "Fatoumatta Jallow",
    verifiedOn: "26 May 2026",
    employerViews: 11,
  },
  {
    id: "pp-3",
    competency: "SQL querying",
    courseSlug: "data-analytics-foundations",
    evidenceTitle: "Twelve queries against the clinic warehouse",
    evidenceSummary:
      "Joins across four tables, a window function for month-on-month change, and a written explanation of each result.",
    status: "verified",
    verifiedBy: "Fatoumatta Jallow",
    verifiedOn: "18 June 2026",
    employerViews: 14,
  },
  {
    id: "pp-4",
    competency: "Dashboard design",
    courseSlug: "data-analytics-foundations",
    evidenceTitle: "Kanifing clinic waiting-time dashboard",
    evidenceSummary:
      "Three screens for a clinic manager on a shared desktop: today, this week, and the one number that triggers a staffing call.",
    status: "in-review",
    submittedOn: "22 September 2026",
    employerViews: 0,
  },
  {
    id: "pp-5",
    competency: "Data storytelling",
    courseSlug: "data-analytics-foundations",
    evidenceTitle: "Capstone decision memo",
    evidenceSummary: "",
    status: "not-started",
    employerViews: 0,
  },
];

export const learners: Learner[] = [
  {
    id: "l-1",
    name: "Awa Sanneh",
    cohort: "Data — Sept 2026",
    courseSlug: "data-analytics-foundations",
    mode: "onsite",
    progress: 82,
    verified: 4,
    pending: 1,
    lastActive: "2 hours ago",
    risk: "on-track",
    location: "Kanifing",
    note: "Strongest capstone draft in the cohort. Ready for employer introduction.",
  },
  {
    id: "l-2",
    name: "Sulayman Jarju",
    cohort: "Data — Sept 2026",
    courseSlug: "data-analytics-foundations",
    mode: "live",
    progress: 64,
    verified: 3,
    pending: 1,
    lastActive: "yesterday",
    risk: "on-track",
    location: "Brikama",
    note: "Joins every live session. SQL joins still shaky — paired with Awa.",
  },
  {
    id: "l-3",
    name: "Haddy Sillah",
    cohort: "Data — Sept 2026",
    courseSlug: "data-analytics-foundations",
    mode: "self-paced",
    progress: 31,
    verified: 1,
    pending: 0,
    lastActive: "11 days ago",
    risk: "at-risk",
    location: "Basse",
    note: "Network outages in Basse. Offered an onsite transfer for module 3.",
  },
  {
    id: "l-4",
    name: "Yankuba Gomez",
    cohort: "Software — Aug 2026",
    courseSlug: "front-end-web-development",
    mode: "onsite",
    progress: 74,
    verified: 5,
    pending: 1,
    lastActive: "4 hours ago",
    risk: "on-track",
    location: "Bakau",
    note: "Shipped the capstone under budget at 148KB. Wants a fintech placement.",
  },
  {
    id: "l-5",
    name: "Adama Bojang",
    cohort: "Software — Aug 2026",
    courseSlug: "front-end-web-development",
    mode: "live",
    progress: 48,
    verified: 2,
    pending: 2,
    lastActive: "3 days ago",
    risk: "watch",
    location: "Serrekunda",
    note: "Two submissions waiting on me, not on her. Clear the queue first.",
  },
  {
    id: "l-6",
    name: "Momodou Faal",
    cohort: "Security — Sept 2026",
    courseSlug: "cybersecurity-fundamentals",
    mode: "onsite",
    progress: 57,
    verified: 3,
    pending: 1,
    lastActive: "6 hours ago",
    risk: "on-track",
    location: "Banjul",
    note: "Works nights at a bank. Writes the clearest incident briefs I have read.",
  },
  {
    id: "l-7",
    name: "Fatou Camara",
    cohort: "Fintech — Sept 2026",
    courseSlug: "mobile-money-and-fintech-operations",
    mode: "live",
    progress: 69,
    verified: 4,
    pending: 0,
    lastActive: "yesterday",
    risk: "on-track",
    location: "Serrekunda",
    note: "Already an agent supervisor. Reconciliation module was revision for her.",
  },
  {
    id: "l-8",
    name: "Ismaila Dibba",
    cohort: "Climate — Sept 2026",
    courseSlug: "agri-data-and-climate-monitoring",
    mode: "onsite",
    progress: 44,
    verified: 2,
    pending: 1,
    lastActive: "2 days ago",
    risk: "watch",
    location: "Janjanbureh",
    note: "Missed the second field weekend — travel cost. Stipend approved.",
  },
  {
    id: "l-9",
    name: "Nyima Touray",
    cohort: "Digital Business — Sept 2026",
    courseSlug: "digital-marketing-and-growth",
    mode: "self-paced",
    progress: 91,
    verified: 4,
    pending: 0,
    lastActive: "5 hours ago",
    risk: "on-track",
    location: "Brufut",
    note: "Ran her own shop's campaign as the capstone. Revenue up 34% in two weeks.",
  },
  {
    id: "l-10",
    name: "Kebba Sanyang",
    cohort: "Data — Sept 2026",
    courseSlug: "data-analytics-foundations",
    mode: "self-paced",
    progress: 12,
    verified: 0,
    pending: 0,
    lastActive: "3 weeks ago",
    risk: "at-risk",
    location: "Soma",
    note: "No submissions yet. Called twice, no answer. Flagged for outreach.",
  },
];

export const learnerById = (id: string) => learners.find((l) => l.id === id);

export const evidenceQueue: EvidenceItem[] = [
  {
    id: "ev-1",
    learnerId: "l-1",
    courseSlug: "data-analytics-foundations",
    competency: "Dashboard design",
    title: "Kanifing clinic waiting-time dashboard",
    submitted: "22 September 2026",
    summary:
      "Three screens for a clinic manager on a shared desktop: today, this week, and the one number that triggers a staffing call. Includes a short note on why she dropped two charts from the first draft.",
    artefacts: [
      "dashboard-v3.pdf (4 pages)",
      "waiting-times-clean.csv (8,412 rows)",
      "design-notes.md",
    ],
    rubric: [
      {
        criterion: "Chart choice matches the question",
        met: true,
        note: "Line for trend, single big number for the trigger. Correct restraint.",
      },
      {
        criterion: "Labelling is unambiguous",
        met: true,
        note: "Units and dates on every axis. Legend removed where colour is obvious.",
      },
      {
        criterion: "Designed for the real device",
        met: true,
        note: "Tested at 1366×768, the actual clinic desktop resolution.",
      },
      {
        criterion: "Explains what to do with it",
        met: false,
        note: "The staffing trigger is shown but the threshold is never justified.",
      },
    ],
    aiDraft:
      "Awa — this is close to ready. The restraint in your third draft is the best thing about it: dropping the two extra charts made the staffing trigger impossible to miss, and your design notes explain that choice well.\n\nOne gap before I can verify it. You show the trigger at 45 minutes but never say where 45 came from. A clinic manager will ask that in the first minute. Add two or three sentences: what the historical distribution looks like, and why 45 is the point where waiting turns into people leaving without being seen. If the number came from the cohort discussion rather than the data, say that too — a stated assumption is fine, an unstated one is not.\n\nResubmit with that paragraph and I will sign this off for your passport.",
    status: "queued",
  },
  {
    id: "ev-2",
    learnerId: "l-5",
    courseSlug: "front-end-web-development",
    competency: "Accessible forms",
    title: "Agent sign-up form, keyboard-only pass",
    submitted: "20 September 2026",
    summary:
      "A four-field registration form with inline validation, completed end to end without a mouse and with a screen reader running. Includes a recording of the keyboard pass.",
    artefacts: [
      "form.html",
      "keyboard-pass.mp4 (1:48)",
      "axe-report.json (0 violations)",
    ],
    rubric: [
      {
        criterion: "Every input has a real label",
        met: true,
        note: "Labels are associated, not placeholder-only. Good.",
      },
      {
        criterion: "Errors are announced, not just coloured",
        met: true,
        note: "aria-live region reads the error text. Verified in the recording.",
      },
      {
        criterion: "Focus order is logical",
        met: true,
        note: "Tab order follows the visual order including the error summary.",
      },
      {
        criterion: "Works without JavaScript",
        met: false,
        note: "Submitting with JS disabled loses the form values.",
      },
    ],
    aiDraft:
      "Adama — the keyboard pass is genuinely good work and the recording made it quick to check. Labels, focus order and the live region are all correct, and a clean axe report on a form with inline validation is not easy.\n\nThe one thing holding it back: with JavaScript disabled the form loses everything the user typed. For an agent signing up on a slow connection, that is the most likely failure of all. Make the form submit to a server endpoint by default and treat your JavaScript validation as an enhancement on top.\n\nFix that and this competency is verified. You are ahead of where this module usually sits at week 6.",
    status: "queued",
  },
  {
    id: "ev-3",
    learnerId: "l-6",
    courseSlug: "cybersecurity-fundamentals",
    competency: "Incident reporting",
    title: "Phishing simulation — one-page brief to a director",
    submitted: "19 September 2026",
    summary:
      "A one-page write-up of the cohort phishing simulation: 34% click rate, which departments, and three changes ranked by cost.",
    artefacts: ["incident-brief.pdf (1 page)", "simulation-results.xlsx"],
    rubric: [
      {
        criterion: "Leads with the finding",
        met: true,
        note: "First sentence states the click rate and the risk. Exactly right.",
      },
      {
        criterion: "No unexplained jargon",
        met: true,
        note: "Uses 'credential reuse' and then explains it in six words.",
      },
      {
        criterion: "Recommendations are costed",
        met: true,
        note: "Three actions, each with an effort estimate and an owner.",
      },
      {
        criterion: "Fits on one page",
        met: true,
        note: "It does, and it is still readable. Rare.",
      },
    ],
    aiDraft:
      "Momodou — verified, with nothing held back. This is the standard the module is aiming at and I am going to use it as the worked example for the next cohort, with your permission.\n\nWhat makes it work: you lead with 34% in the first sentence, you name the two departments without blaming individuals, and each of your three recommendations has a cost next to it so the director can choose rather than nod. The line explaining credential reuse in six words is the sort of thing most people take a paragraph to do badly.\n\nOne thing to carry forward, not a correction: when you write the next one for a real incident rather than a simulation, add a 'what we still do not know' line. Directors trust a brief more when it admits its edges.",
    status: "queued",
  },
  {
    id: "ev-4",
    learnerId: "l-8",
    courseSlug: "agri-data-and-climate-monitoring",
    competency: "Field data collection",
    title: "Rain gauge placement and two weeks of readings",
    submitted: "16 September 2026",
    summary:
      "Six gauges sited across two groundnut plots, with a siting rationale, calibration log and fourteen days of twice-daily readings.",
    artefacts: [
      "siting-rationale.pdf",
      "calibration-log.csv",
      "readings-sept.csv (168 rows)",
      "plot-photos.zip (14 images)",
    ],
    rubric: [
      {
        criterion: "Siting is justified against guidance",
        met: true,
        note: "Cites clearance distances and explains the one gauge that breaks them.",
      },
      {
        criterion: "Calibration is logged",
        met: true,
        note: "Pre- and post-period checks on all six gauges.",
      },
      {
        criterion: "Readings are complete",
        met: false,
        note: "Four missing readings on 9–10 September with no note explaining why.",
      },
      {
        criterion: "Photographs support the record",
        met: true,
        note: "Each gauge photographed in situ with a scale reference.",
      },
    ],
    aiDraft:
      "Ismaila — the siting work here is careful and the calibration log is exactly what the module asks for. Explaining why gauge 4 breaks the clearance guidance, instead of hiding it, is the right instinct.\n\nThe blocker is small but it matters: four readings are missing on 9 and 10 September with nothing said about it. In field data a gap with no explanation is worse than a gap with one, because the next person cannot tell whether it rained or whether nobody walked out. Add a line to the log for each missing slot saying what happened, even if the answer is that you were travelling.\n\nDo that and this is verified. And the missed field weekend is sorted — your travel stipend is approved, so plan to be at the October session.",
    status: "queued",
  },
];

export const countryDemand: CountryDemand[] = [
  {
    code: "GM",
    country: "The Gambia",
    learners: 1840,
    openRoles: 132,
    topSkill: "Data cleaning",
    gap: 41,
  },
  {
    code: "SN",
    country: "Senegal",
    learners: 1120,
    openRoles: 204,
    topSkill: "SQL querying",
    gap: 58,
  },
  {
    code: "GH",
    country: "Ghana",
    learners: 960,
    openRoles: 287,
    topSkill: "React components",
    gap: 63,
  },
  {
    code: "NG",
    country: "Nigeria",
    learners: 1430,
    openRoles: 512,
    topSkill: "Fraud detection",
    gap: 67,
  },
  {
    code: "CI",
    country: "Côte d'Ivoire",
    learners: 710,
    openRoles: 168,
    topSkill: "Payments reconciliation",
    gap: 55,
  },
  {
    code: "SL",
    country: "Sierra Leone",
    learners: 480,
    openRoles: 74,
    topSkill: "Incident reporting",
    gap: 38,
  },
  {
    code: "LR",
    country: "Liberia",
    learners: 320,
    openRoles: 51,
    topSkill: "Linux administration",
    gap: 34,
  },
  {
    code: "GN",
    country: "Guinea",
    learners: 405,
    openRoles: 62,
    topSkill: "Field data collection",
    gap: 31,
  },
  {
    code: "GW",
    country: "Guinea-Bissau",
    learners: 190,
    openRoles: 28,
    topSkill: "Data cleaning",
    gap: 29,
  },
  {
    code: "TG",
    country: "Togo",
    learners: 355,
    openRoles: 66,
    topSkill: "Dashboard design",
    gap: 36,
  },
  {
    code: "BJ",
    country: "Benin",
    learners: 380,
    openRoles: 71,
    topSkill: "KYC & compliance",
    gap: 39,
  },
  {
    code: "CV",
    country: "Cabo Verde",
    learners: 145,
    openRoles: 33,
    topSkill: "Observability",
    gap: 44,
  },
];

export const skillGapData = [
  { skill: "SQL querying", verified: 214, roles: 318 },
  { skill: "Data cleaning", verified: 286, roles: 341 },
  { skill: "React components", verified: 138, roles: 262 },
  { skill: "Fraud detection", verified: 74, roles: 196 },
  { skill: "Linux administration", verified: 91, roles: 174 },
  { skill: "Threat modelling", verified: 112, roles: 188 },
  { skill: "Dashboard design", verified: 167, roles: 203 },
  { skill: "Field data collection", verified: 88, roles: 97 },
];

export const gapTrend = [
  { month: "Apr", gap: 61, verified: 540 },
  { month: "May", gap: 58, verified: 612 },
  { month: "Jun", gap: 54, verified: 704 },
  { month: "Jul", gap: 51, verified: 798 },
  { month: "Aug", gap: 46, verified: 902 },
  { month: "Sep", gap: 43, verified: 1024 },
];

export const modeSplit = [
  { mode: "Onsite", learners: 2940, fill: "var(--color-blue-600)" },
  { mode: "Live tutor-led", learners: 3420, fill: "var(--color-blue-300)" },
  { mode: "Self-paced", learners: 1975, fill: "var(--color-gold-400)" },
];

export const cohortProgress = [
  { week: "W1", onsite: 8, live: 7, self: 6 },
  { week: "W3", onsite: 24, live: 22, self: 15 },
  { week: "W5", onsite: 41, live: 38, self: 24 },
  { week: "W7", onsite: 58, live: 54, self: 33 },
  { week: "W9", onsite: 72, live: 68, self: 41 },
  { week: "W11", onsite: 86, live: 81, self: 49 },
];

export const journeySteps = [
  {
    id: "compass",
    name: "Career Compass",
    short: "AI recommends your path",
    href: "/student/compass",
    detail:
      "Five questions about your background and your constraints, then a track and the first course in it.",
  },
  {
    id: "studio",
    name: "Learning Studio",
    short: "Hybrid, hands-on courses",
    href: "/student/studio",
    detail:
      "Nine courses, each available onsite, live with a tutor, or self-paced. A module closes when you can do the thing.",
  },
  {
    id: "passport",
    name: "Skills Passport",
    short: "Verify what you can do",
    href: "/student/passport",
    detail:
      "Every skill is backed by work a tutor reviewed. One record that grows instead of resetting each course.",
  },
  {
    id: "bridge",
    name: "Talent Bridge",
    short: "Match to real employers",
    href: "/student/bridge",
    detail:
      "Employers search verified skills, not degree names. Every match shows the reason it was made.",
  },
  {
    id: "intelligence",
    name: "Regional Intelligence",
    short: "Data feeds back to ECOWAS",
    href: "/educator/intelligence",
    detail:
      "Anonymised supply and demand per country, so educators and ministries see which gaps are widening.",
  },
];

export const studentProfile = {
  name: "Awa Sanneh",
  initials: "AS",
  cohort: "Data — Sept 2026",
  location: "Kanifing, The Gambia",
  joined: "March 2026",
  passportId: "ENL-GM-2026-04182",
};

export const educatorProfile = {
  name: "Fatoumatta Jallow",
  initials: "FJ",
  title: "Lead tutor, Data practice",
  location: "Ednovate Lab, Kanifing",
  cohorts: 3,
};
